# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    logo:
      text: "Jinwei Hu's Portfolio"

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Jinwei Hu.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false


# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
